### ISSUE TITLE
query parameter not work with latest nextjs

### ISSUE THREAD

**Issue by derit** [tscanlin/next-blog#12]
i'm test with build using latest nextjs version, query parameter is not work for load json with current url path 

in this case when i click read more (url) to view article details, it work, and have a problem when i reload the article,  showing the blank screen

**Comment by tscanlin** [comment]
is this once its deployed? or during development?

**Comment by derit** [comment]
@tscanlin during development

**Comment by tscanlin** [comment]
Can you include the error here?

**Comment by tscanlin** [comment]
I haven't been able to reproduce this. Let me know if you can provide more info.

**Comment by tscanlin** [comment]
this should be fixed in the latest build `3.2.0`
