### ISSUE TITLE
Not rendering latex, processmd set to render latex: true

### ISSUE THREAD

**Issue by eleijonmarck** [tscanlin/next-blog#13]
Not rendering latex, processmd set to render latex: true

Proceeding the installation specifications. I am unable to get the following change to `first-post.md` to render latex.

```bash
$ cat first_post.md
---
title: First post
date: 2017-06-01
---

First post!

Checkout [github to see my other projects](github.com/tscanlin)

[another page](/custom-post)

Math;

$ x = y $
```

after the change to the post.

I run `rm -rf content/summary.json` and && `npm run build:content`

![image](https://user-images.githubusercontent.com/7727602/65885832-958d1d00-e39b-11e9-9b18-3cde035b6549.png)

**Expected**
To get mathematical syntax highlight

**Comment by tscanlin** [comment]
Can you pass the option to processmd via `markdownOptions`?
See:
https://github.com/tscanlin/processmd/blob/1d5aa8a32829e9b54bc93849c94de2976ae88233/index.test.js#L176

for example:
```
processmd content/**/*.md --outputDir content --preview 110 --summaryOutput content/summary.json --markdownOptions '{"latex":true}'
```

**Comment by eleijonmarck** [comment]
@tscanlin could not get it to work with using the example.


```package.json
...
    "build:content:test": "processmd content/**/*.md --outputDir content --preview 110 --summaryOutput content/summary.json --markdownOptions '{\"latex\":true}'",
....
```

i ran:
```bash 
git clone repo
npm install
npm run build:content:test
npm start
```

but to no avale. Could you see if you can make it work?

**Comment by tscanlin** [comment]
I looked into this a bit more and it should be enabled by default (https://github.com/tscanlin/processmd/blob/master/defaultOptions.js#L13).
Try:
```
`$ x = y $`
```

**Comment by tscanlin** [comment]
that worked for me

**Comment by eleijonmarck** [comment]
@tscanlin 

when changing from

```
x = y
```

to:
```
`x = y`
```

i get:

![image](https://user-images.githubusercontent.com/7727602/66339447-78c88a80-e943-11e9-9691-c2503196d434.png)

**Comment by tscanlin** [comment]
That example may be too simple. Can you try this?
```
`$E = mc^2$`
```

**Comment by tscanlin** [comment]
Oh I see what is needed, can you add this CSS to your page?
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous" />
```

**Comment by tscanlin** [comment]
<img width="494" alt="Screen Shot 2019-10-07 at 7 25 49 PM" src="https://user-images.githubusercontent.com/5033032/66362610-52e9b880-e938-11e9-8e5b-8ef8773653b4.png">

**Comment by eleijonmarck** [comment]
@tscanlin hmm I still cant get it to work actually. But that looks good.

Exactly where did you add that link?

I added it to the blogs themselves, as html is a subset of markdown.

**Comment by tscanlin** [comment]
I added the link in the head component. Src/components/Header. Hope that works for you, please let me know!

**Comment by tscanlin** [comment]
@eleijonmarck were you able to get this working?

**Comment by eleijonmarck** [comment]
@tscanlin  cool. Yea I got it to work now.

![image](https://user-images.githubusercontent.com/7727602/67844965-ef017c80-fafe-11e9-8f66-d5709e9c0cb0.png)

For all those that needs help with understanding where to add the link
```bash
$ cat src/components/Header.js 
```
```js
import React from 'react'
import PropTypes from 'prop-types'
import Head from 'next/head'

function Header(props) {
  return (
    <Head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous" />
```
